### ISSUE TITLE
[Proposal] Update Initialization and Clean Rule for libft Submodule

### ISSUE THREAD

**Issue by rask24** [alex216/ft_pipex#37]
## Issue Summary
There appears to be a challenge with the current setup and cleanup process for the `libft` submodule. Specifically, the initialization of `libft` and the behavior of the `make clean` command when `libft` is not initialized properly.

### Initialization of libft
I propose adjusting the initialization sequence of `libft` to ensure a smoother setup process.

```
$(NAME): $(LIB) $(SRCS)
@make man_step_0 $(DEBUG_FLAG)

$(LIB):
@git submodule update --init --recursive
@make -C ./libft
```

### Modification to the Clean Rule
Currently, if the `libft` submodule is not initialized, running `make clean` results in an ERROR. To address this, it would be beneficial to modify the clean rule to ignore errors for the `libft` submodule. Suggested modification:

```
clean:
-@make -s -C ./libft clean
```

This change uses the `-` prefix to ignore errors specifically from the `libft` cleanup command, ensuring that the `make clean` process completes successfully regardless of the `libft` initialization state.

## Conclusion
These proposed adjustments aim to enhance the development experience by ensuring more robust setup and cleanup procedures for the `libft` submodule. Feedback and further suggestions are welcome.

**Comment by alex216** [comment]
thx dude, ggwp.
fixed \@bb9696c.
